### ISSUE TITLE
Chrome not updated error

### ISSUE THREAD

**Issue by janecakemaster** [popcodeorg/popcode#192]
we don't always have control over the school computers. what's the latest version of chrome supported/can we try to support some of the minor older versions? is safari or firefox better for handling pop code?

**Comment by outoftime** [comment]
@janecakemaster if you’re seeing the out-of-date browser error, it’s because Popcode is known to be totally broken on that browser version, and supporting it would require a major overhaul of some aspect of Popcode’s implementation (generally in a way that would make Popcode harder to maintain). The unsupported browser versions are generally at least 2–3 years old, which I realize doesn’t stop them from being on school computers, but one must draw the line somewhere.

Popcode has no preference between Chrome/Firefox/Safari, and might even work decently in IE; it’s really just a matter of which browser you happen to have access to a recent version of. Have you run into a situation where *none* of the browsers installed on a school computer have been able to run Popcode?

**Comment by outoftime** [comment]
BTW, source of truth for supported browsers [here](https://github.com/popcodeorg/popcode/blob/master/config/browsers.json) (listed versions are oldest supported)

**Comment by outoftime** [comment]
@janecakemaster I’m going to close this for now—feel free to ping again if you’re in a situation where your students can’t run Popcode on any browser they have access to.
