### ISSUE TITLE
Students lose work when logging out of other student’s account

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#216]
Submitter: Sharang Phadke
When I click "New Project", all my code is erased. There should be a way to undo this!

**Comment by SharangP** [comment]
Ok, that description was obviously not very detailed. Here's a real description:

The issue is related to dealing with github login state. It occurs when a student has started working on a project in popcode without first logging out the previous user. Often, the student doesn't realize this until the end of the class, when all their work is already entered into popcode. When the student then tries to log out and back in, popcode deletes all their work upon log-out, without warning. There is no way to recover this code. 

A separate issue is that the new project button, which I would expect to open a new empty popcode tab, actually clears all the code in the current tab. In today's world of UX, I think this violates the principle of least surprise.

Here are a few solutions that may mitigate this problem:
1. "new project" should open a new tab! At the cost of having to log in again, this will probably save several students' work over the course of the year.
1. Add an in-window message or popup after 1? hour of inactivity, asking “hey, are you still logged in as this user? If not, <log out here> or <ignore>”. For classes that run once a day, this will prompt students to deal with logging out and back in at the very beginning of the class.

**Comment by outoftime** [comment]
Hi @SharangP ,

Definitely some real issues here, but I did want to clarify a couple of things:

> Often, the student doesn't realize this until the end of the class, when all their work is already entered into popcode. When the student then tries to log out and back in, popcode deletes all their work upon log-out, without warning. There is no way to recover this code.

The code can definitely be recovered in this situation—simply log back in to the account of the student that was initially (incorrectly) logged in. The work will be stored in that student’s projects; you can find it with the “Load Project” button.

> A separate issue is that the new project button, which I would expect to open a new empty popcode tab, actually clears all the code in the current tab.

In this situation, the student is also able to go back to the previous project using the “Load Project” button. I agree that the interface could perhaps make this more obvious, although at least in my classroom this seems to have been reasonably discoverable for the students.

Overall, just wanted to assure you that in no situation will Popcode discard the code of a logged in student—it will always be saved to their account.

**Comment by SharangP** [comment]
Hi there, sorry for a late response:

Re: recovering code by logging back in - great, I had no idea. It's definitely a bit unintuitive, I'm wondering whether we can make this interface for recovering lost work more obvious? 

Re: "Load Project" re-loading a previous project - this is also nice. But I still think it makes sense to have "New Project" open in a new tab, at the cost of requiring the student to log in again. What do you think?

When you say that the code of a logged in student is always saved to their account, do you mean it's just cached locally until the tab is closed? Or can a recent (but un-exported) project be loaded across tabs / user sessions via some sort of remote / server caching?

**Comment by outoftime** [comment]
@SharangP 

> It's definitely a bit unintuitive, I'm wondering whether we can make this interface for recovering lost work more obvious?

I’m definitely interested to hear ideas! Is the unintuitive part that the code on screen goes away when you log out?

> Re: "Load Project" re-loading a previous project - this is also nice. But I still think it makes sense to have "New Project" open in a new tab, at the cost of requiring the student to log in again. What do you think?

I have to say I disagree—the “New Project” behavior is pretty standard, I think (JS Bin does the exact same thing, anyway). And given how bad network conditions are in most classrooms, opening a new instance of Popcode would involve a significant wait time (ditto for logging back in). Also, I have to say that the students in my class, at least, don’t seem to be getting tripped up by the way it works today.

> When you say that the code of a logged in student is always saved to their account, do you mean it's just cached locally until the tab is closed? Or can a recent (but un-exported) project be loaded across tabs / user sessions via some sort of remote / server caching?

It’s saved remotely and permanently—any time a student logs in, they can access all the work they’ve done (while logged in) via the “Load Project” button.

**Comment by outoftime** [comment]
The big pain point here is fixed by #635
