### ISSUE TITLE
Popout webpage no longer works

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#505]
When students would like to view their creations in full screen that can click on the icon on the top right of the webpage render.

On the current build of Popcode clicking this button will immediately cause the window to close.

**Comment by outoftime** [comment]
Good catch @jwang1919 !

I suspect this may actually be a Chrome bug—we saw the same behavior when I changed a seemingly-inconsequential line of code to call `window.open()` directly with a data URI, rather than opening with `about:blank` and then setting the `window.location` to the data URI (which works fine).

The pop-out has always used the former approach—and it used to work, which is why I suspect this might be a bug in the current version of Chrome. (Note that pop-out works fine in Firefox as of this writing).

Anyway, pretty easy fix—just need to change the pop-out to do the same behavior (first open `about:blank`, then set `window.location.href`).

**Comment by jwang1919** [comment]
Yeah I just noticed this when playing around with Popcode while working on next week's lesson.
