### ISSUE TITLE
Students often refresh the page and lose all their work

### ISSUE THREAD

**Issue by ibrand** [popcodeorg/popcode#676]
This is definitely user error in a lot of ways, but I think it would be great to make saving more a part of the workflow. My proposal is that `ctrl + s` would "save" which, judging by popcode's current functionality, would probably just be exporting a gist somewhere that each subsequent save would overwrite.

Seems like an approachable way to start solving this problem.

**Comment by outoftime** [comment]
@ibrand are you observing this while students are logged out? if they’re logged in, their work is automatically saved—they can just bring up the project they were working on using **Load Project**. if that’s insufficiently discoverable, i think we just have a UX problem

in the case where the student is logged out, though, it’s a definite problem. there is a pop-up warning before refresh but of course everyone ignores those.

i don’t think we need to do anything as complicated as getting gists involved—`sessionStorage` should do the trick. i think the [enhancement outlined here](https://github.com/popcodeorg/popcode/issues/609) would provide a robust solution.

WDYT?

**Comment by ibrand** [comment]
Wow. I actually didn't know about that feature. That is so convenient! I'm noticing that when I use it on my account it looks like this:

<img width="300" alt="screen shot 2017-02-17 at 7 08 03 pm" src="https://cloud.githubusercontent.com/assets/3953117/23087737/86d53a38-f544-11e6-96b9-f13094e8cbc2.png">

and I assume that the "a few seconds ago" text is what's telling me which gist I can load. Should it have more information in it? Or a slightly different UI? When I initially saw it, I wasn't sure if I could click it because it looks very similar to the state in which I have no saved gists

**Comment by inlinestyle** [comment]
I also did not know about the "Project" functionality available to the students when they log in. Just knowing about it is going to be so helpful going forward (students really do refresh all the time).

I wonder if there's a way we can make the existing functionality more visible? I think it doesn't occur to students (or their teachers) that "Load Project" will give them access to something they didn't knowingly create.

Perhaps flashing a notification or snackbar suggesting loading the latest project when a logged in user arrives at the page?

I wonder if it would also be helpful to persist the ID of an explicitly loaded project across page refreshes (in the URL or something).

I'd be happy to help implement any UI updates to make people more aware of this!

**Comment by outoftime** [comment]
> I wonder if there's a way we can make the existing functionality more visible?

Yeah, we definitely need to do this. Generally I think Popcode needs a layout refresh which, among other things, should solve the problem of current features being insufficiently discoverable.

[This issue](https://github.com/popcodeorg/popcode/issues/638) has some interesting explorations of what it might look like to have a compressed but always-open dashboard; the [original design workups](https://github.com/popcodeorg/popcode-assets/blob/master/Popcode_identity_051616.pdf) (scroll to the fourth slide) also contemplated a top bar which contains a lot of the functionality of the current dashboard.

> Perhaps flashing a notification or snackbar suggesting loading the latest project when a logged in user arrives at the page?

That’s an interesting idea. Until a couple of months ago, Popcode would actually load the most recent project automatically if you logged in immediately after loading the app. We moved away from that for various good reasons, but I do like the idea of calling out the most recent project in some way.

> I wonder if it would also be helpful to persist the ID of an explicitly loaded project across page refreshes (in the URL or something).

I’ve been pretty firmly opposed to doing the JS Bin-style URL persistence, mostly because it opens up a whole can of worms around what happens if you give the URL to someone else and they try to load it. At this point I’m still more inclined to focus on making the existing persistence functionality more discoverable (and as a corollary, making it more obvious that your work is _not_ going to be saved if you’re logged out—the way CodePen does this seems like a good starting point).

**Comment by inlinestyle** [comment]
I love the perma-header idea. Moving discussion to  https://github.com/popcodeorg/popcode/issues/779

**Comment by outoftime** [comment]
I still think this is an important issue, but I’m going to close this as we’ve got a couple of ideas to address it in #779 and #609.
