### ISSUE TITLE
Incidental infinite loop breaks PopCode

### ISSUE THREAD

**Issue by marcianx** [popcodeorg/popcode#706]
Say, someone writes the following on PopCode:

```javascript
for (var i = 0; i < 10; i = i + 1) {
}
```

and then copy-pastes it to create a nested loop

```javascript
for (var i = 0; i < 10; i = i + 1) {
    for (var i = 0; i < 10; i = i + 1) {
    }
}
```

Then, the user changes the `i`'s to `j`'s (cursor shown as | below).

```javascript
for (var i = 0; i < 10; i = i + 1) {
    for (var j = 0; j| < 10; i = i + 1) {
    }
}
```

As soon as the second `j` is changed, PopCode auto-runs this and ends up in an infinite loop since `j` is never incremented. The UI becomes unresponsive until Chrome eventually times out and asks to kill the session, which loses all existing work.

**Comment by outoftime** [comment]
Thanks @marcianx!

Looks like this is a deficiency in [`loop-protect`](https://github.com/jsbin/loop-protect), which Popcode uses to break infinite loops. I’ve filed [an issue](https://github.com/jsbin/loop-protect/issues/16) with that project, although I’m not sure how maintained it is at this point; we may need to look into patching it or replacing it with something AST-based.

**Comment by outoftime** [comment]
N.B. it seems like it would be not that crazy to rewrite the script injection part of `loop-protect` to use [`recast`](https://github.com/benjamn/recast) rather than a heuristic regexp.

[This post](https://codepen.io/quezo/post/stopping-infinite-loops) and [this followup](https://codepen.io/quezo/post/improving-infinite-loop-detection) on the CodePen blog are worth studying for potential pitfalls; unfortunately it doesn’t seem like they’ve open-sourced their solution.
