### ISSUE TITLE
Closing CSS/Javascript doesn't expand view for html box

### ISSUE THREAD

**Issue by sarahzinger** [popcodeorg/popcode#782]
Ran into a minor styling bug: 
![wz2ifqzyoc](https://cloud.githubusercontent.com/assets/6620164/25112741/3032d8a6-23c1-11e7-9fa3-5f9a8e45d954.gif)

**Comment by outoftime** [comment]
@sarahzinger you are absolutely right which is weird because [I totally fixed this issue once already](https://github.com/popcodeorg/popcode/pull/128)! But it does not appear to work now.

Took a quick glance and the [`_resize()` call](https://github.com/popcodeorg/popcode/blob/master/src/components/Editor.jsx#L85) is happening, so maybe it’s being called too soon for the editor to properly infer its size?

**Comment by ianmclaury** [comment]
In case it helps diagnose the problem, I noticed if you click on the unpainted / blank area the missing html will suddenly appear.

**Comment by outoftime** [comment]
thanks @ianmclaury! that is expected since we do explicitly listen for the focus event on the editor and tell it to resize at that time, but that should really be a fallback for resizing when the actual container resizes.
