### ISSUE TITLE
Store visible/hidden tile state, perhaps in URL?

### ISSUE THREAD

**Issue by ajgreenb** [popcodeorg/popcode#799]
Apologies if this is the wrong place to put enhancement ideas, or if this enhancement has been previously suggested (I searched but couldn't find it.) The idea is to store in the URL which of the Popcode tiles (HTML/CSS/JavaScript/Output) are currently visible. This way, when sharing a link to a Gist, unimportant tiles will remain minimized. CodePen does this using a bitmask (`?editors=1011`); we could steal their implementation?

**Comment by outoftime** [comment]
This is definitely the right place for enhancement ideas!

Making editor open/close state sticky is a good idea and we should do it. This has come up before but I don’t think it was captured in an issue, so thank you!

I think the move would be to store it in the `popcode.json` metadata “file” in the gist export, analogously to how we persist enabled libraries.

**Comment by marcianx** [comment]
I'd argue that the URL approach is better than sitting it in JSON. That way one didn't have to exit as gist just to change the initial UI state.
Either way, though, I'd be happy to see the feature implemented. :)

**Comment by ajgreenb** [comment]
@marcianx Storing state in the URL is convenient for sure, but I can also see @outoftime's perspective—Popcode currently doesn't store *any* state in the URL so if you want to share a project with your students, you'd have to export it anyway.

I imagine that if Popcode started storing *some* state in the URL, it would make sense to store *all* state in the URL. That way you'd be able to rehydrate an entire project from a link. But exporting as a Gist seems to fully cover the use case of creating a starter template with some pre-configuration to share with students.

**Comment by outoftime** [comment]
Definitely agree that minimized editor state isn’t as obviously a project-level concern as, say, enabled libraries. However, the outcome of treating it that way in #806 is quite good, I think—in particular, minimized state is not only persisted in gists, but also persisted when switching between saved projects. I think this makes a ton of sense!

Anywho, let’s see how it feels when it’s in the gist export, and we can definitely reopen the discussion about URLs if it is still a pain point. One this specific tip, though:

> it seems a little strange to need to re-persist the code just to modify which tabs in the UI we want our audience to currently focus on

I’ve long wanted an “update gist” function to update a gist that you’ve already exported from a given project, rather than having to create a new gist every time. That would probably ease this particular pain a bit?
