### ISSUE TITLE
Font colors should meet accessibility standards

### ISSUE THREAD

**Issue by kaylee42** [popcodeorg/popcode#863]
All icons and fonts should meet current accessibility standards for color contrast (specifically the pop out icon, HTML/CSS/JS icons do not meet standards) 

https://hexnaw.com/ is good resource for checking color contrast accessibility

**Comment by ibrand** [comment]
So it's actually not until you have `opacity: 0.5` that the buttons technically meet the accessiblity standard. Curious what we think about this since it's a very different UI.

<img width="414" alt="screen shot 2017-06-28 at 7 57 35 pm" src="https://user-images.githubusercontent.com/3953117/27665596-1183fa80-5c3c-11e7-9999-c4d1666074c9.png">

**Comment by kaylee42** [comment]
@ibrand I personally think it looks great (as someone who's always had a really hard time seeing them). Also, realized this probably additionally resolves this other issue: https://github.com/popcodeorg/popcode/issues/329

**Comment by outoftime** [comment]
Cosign @kaylee42 I don’t have any objection to the contrast in the screenshot, and anyway I would rather meet the accessibility standard and then work on perfecting the UI than the other way around : )

**Comment by outoftime** [comment]
Fixed by #896
